### ISSUE TITLE
Minimum requirement for aws dependency is too low

### ISSUE THREAD

**Issue by stevenringo** [airplanedev/terraform-aws-airplane-agents#10]
`3.22.0` is too low for aws module as a dependency
`runtime_platform` is unknown with `aws` < `3.70`

**Comment by joshma** [comment]
Hey @stevenringo, apologies for the delayed replies. We'll take a look at this issue and #11 and get back to you soon.

**Comment by joshma** [comment]
Hey @stevenringo , this has been fixed in v0.3.6 - thanks for your patience.
