### ISSUE TITLE
Agents vs tasks in ECS

### ISSUE THREAD

**Issue by stevenringo** [airplanedev/terraform-aws-airplane-agents#11]
Hi,

Is there a reason to have 3 agents running now that ECS/Fargate is being used? I think this made sense in the EC2 version of this, but now with ECS, I am imagining only 1 agent is enough, and it will spawn as many Fargate tasks as needed? Perhaps the limit should be on the number of Fargate tasks? One could get a big Fargate bill if one spawns hundreds of jobs. Thanks

**Comment by joshma** [comment]
Hi @stevenringo , you're correct - it will spawn new tasks for runs. We still recommend 3 agents for availability reasons - the agents act as an extension of the control plane and make scaling decisions, and so we'd want that to continue working even if e.g. certain AWS AZs have issues.

Let me know if that doesn't make sense!
