### ISSUE TITLE
allow use of assign_public_ip = false in aws_ecs_service Resource

### ISSUE THREAD

**Issue by colinbjohnson** [airplanedev/terraform-aws-airplane-agents#28]
# Request

We would like the `assign_public_ip = ` setting to be exposed as a variable so that we can utilize `assign_public_ip = false`.

# Reason

Utilizing private IP addresses (instead of public IPs) allows an additional security control to be implemented and, in many cases, works with an organization's established standard of having resources be internal by default. Recently a customer I worked with had the "Airplane" Task IP addresses flagged as an issue during a network review.

**Comment by yolken-airplane** [comment]
Fixed in https://github.com/airplanedev/terraform-aws-airplane-agents/pull/34.
