### ISSUE TITLE
Name suffix is not applied to task definition

### ISSUE THREAD

**Issue by kartikrao** [airplanedev/terraform-aws-airplane-agents#36]
When a name_suffix is provided, per the documentation it is expected to be applied to the Task Definition as well, however this is not the case.

The problem with this is that we cannot have two deployments of the cluster/agent within the same AWS account as the id will conflict.

In our case we have PROD and NON-PROD AWS account, the NON-PROD account has dev and staging VPC's where we would like to deploy separate cluster/agent.

To reproduce:

```
module "airplane_agent" {
  source  = "airplanedev/airplane-agents/aws"
  version = "0.6.0"
  api_token           = data.aws_ssm_parameter.airplane_api_key.value
  team_id              = var.airplane_team_id
  subnet_ids         = split(",", data.aws_ssm_parameter.vpc_private_subnets.value)

  agent_labels = {
    vpc = data.aws_ssm_parameter.vpc_id.value
    env = var.environment
  }

  name_suffix = "${var.environment}-oracle"
  service_name = "${var.environment}-drive-oracle-service"

  vpc_security_group_ids = [data.aws_ssm_parameter.vpc_default_security_group.value]
  env_slug = var.environment
}
```

Plan Output:

<img width="659" alt="Screen Shot 2023-01-20 at 14 25 33" src="https://user-images.githubusercontent.com/736365/213611308-90f00643-3d94-4743-9b1e-87b1793a29d4.png">

**Comment by yolken-airplane** [comment]
Hi @kartikrao, thanks for this report- we'll have a fix out soon.

**Comment by kartikrao** [comment]
Thank you @yolken-airplane, appreciate the quick resolution.
